/**
 * 巡检管理模块配置
 * 独立模块，规范巡检记录单，保障巡检工作精细完善。
 */

module.exports = {
  id: 'inspection-management',
  name: '巡检管理',
  version: '1.0.0',
  description: '资产日常巡检计划、任务派发、规范巡检记录单与异常问题整改跟踪模块',
  category: '质量与安全',
  type: 'system',
  status: 'stable',
  author: 'System Team',
  created_at: '2026-07-11T00:00:00Z',
  updated_at: '2026-07-11T00:00:00Z',

  dependencies: [
    { module_id: 'asset-management', dependency_type: 'required', min_version: '1.0.0' },
    { module_id: 'user-management', dependency_type: 'required', min_version: '1.0.0' },
  ],

  features: {
    inspection_templates: {
      enabled: true,
      name: '巡检模板',
      description: '可配置的巡检项模板，规范巡检内容',
      configurable: true,
      default_enabled: true,
    },
    inspection_tasks: {
      enabled: true,
      name: '巡检任务',
      description: '基于模板生成的巡检任务派发',
      configurable: true,
      default_enabled: true,
    },
    inspection_records: {
      enabled: true,
      name: '巡检记录单',
      description: '规范的巡检记录单填写与归档',
      configurable: true,
      default_enabled: true,
    },
    issue_tracking: {
      enabled: true,
      name: '异常追踪',
      description: '巡检发现问题整改闭环跟踪',
      configurable: true,
      default_enabled: true,
    },
  },

  frontend_config: {
    menu_keys: [
      '/inspection-parent',
      '/inspection',
      '/inspection/calendar',
      '/inspection/plans',
      '/inspection/routes',
      '/inspection/records',
      '/inspection/templates',
      '/inspection/issues',
      '/inspection/statistics',
    ],
    menu_routes: [
      {
        key: '/inspection-parent',
        icon: 'ReconciliationOutlined',
        label: '巡检管理',
        path: '/inspection-parent',
        permissions: ['inspection:read'],
        order_index: 11.5,
      },
      {
        key: '/inspection',
        label: '巡检任务',
        path: '/inspection',
        component: 'InspectionList',
        parent: '/inspection-parent',
        permissions: ['inspection:read'],
        order_index: 1,
      },
      {
        key: '/inspection/calendar',
        icon: 'CalendarOutlined',
        label: '巡检日历',
        path: '/inspection/calendar',
        component: 'InspectionCalendar',
        parent: '/inspection-parent',
        permissions: ['inspection:read'],
        order_index: 2,
      },
      {
        key: '/inspection/plans',
        icon: 'ScheduleOutlined',
        label: '巡检计划',
        path: '/inspection/plans',
        component: 'InspectionPlans',
        parent: '/inspection-parent',
        permissions: ['inspection:read'],
        order_index: 3,
      },
      {
        key: '/inspection/routes',
        icon: 'EnvironmentOutlined',
        label: '巡检路线',
        path: '/inspection/routes',
        component: 'InspectionRoutes',
        parent: '/inspection-parent',
        permissions: ['inspection:read'],
        order_index: 4,
      },
      {
        key: '/inspection/records',
        label: '巡检记录单',
        path: '/inspection/records',
        component: 'InspectionRecordList',
        parent: '/inspection-parent',
        permissions: ['inspection:read'],
        order_index: 5,
      },
      {
        key: '/inspection/templates',
        icon: 'ProfileOutlined',
        label: '巡检模板',
        path: '/inspection/templates',
        component: 'InspectionTemplateList',
        parent: '/inspection-parent',
        permissions: ['inspection:read'],
        order_index: 6,
      },
      {
        key: '/inspection/issues',
        label: '异常问题',
        path: '/inspection/issues',
        component: 'InspectionIssues',
        parent: '/inspection-parent',
        permissions: ['inspection:read'],
        order_index: 7,
      },
      {
        key: '/inspection/statistics',
        icon: 'BarChartOutlined',
        label: '巡检统计',
        path: '/inspection/statistics',
        component: 'InspectionStatistics',
        parent: '/inspection-parent',
        permissions: ['inspection:read'],
        order_index: 8,
      },
    ],
    components: [
      { name: 'InspectionList', path: 'pages/inspection/InspectionList', export: 'default' },
      { name: 'InspectionRecordList', path: 'pages/inspection/InspectionRecordList', export: 'default' },
      { name: 'InspectionRecordForm', path: 'pages/inspection/InspectionRecordForm', export: 'default' },
      { name: 'InspectionRecordDetail', path: 'pages/inspection/InspectionRecordDetail', export: 'default' },
      { name: 'InspectionTemplateList', path: 'pages/inspection/InspectionTemplateList', export: 'default' },
      { name: 'InspectionTemplateForm', path: 'pages/inspection/InspectionTemplateForm', export: 'default' },
      { name: 'InspectionStatistics', path: 'pages/inspection/InspectionStatistics', export: 'default' },
      { name: 'InspectionIssues', path: 'pages/inspection/InspectionIssues', export: 'default' },
      { name: 'InspectionCalendar', path: 'pages/inspection/InspectionCalendar', export: 'default' },
      { name: 'InspectionPlans', path: 'pages/inspection/InspectionPlans', export: 'default' },
      { name: 'InspectionRoutes', path: 'pages/inspection/InspectionRoutes', export: 'default' },
    ],
    permissions: [
      'inspection:read',
      'inspection:create',
      'inspection:update',
      'inspection:delete',
      'inspection:execute',
      'inspection:review',
    ],
  },

  backend_config: {
    api_prefix: '/api/inspection',
    routes_path: 'routes',
    controllers_path: 'controllers',
    services_path: 'services',
    database_tables: [
      'inspection_templates',
      'inspection_template_items',
      'inspection_tasks',
      'inspection_records',
      'inspection_record_items',
      'inspection_issues',
    ],
    services: [{ name: 'InspectionService', path: 'services/inspection.service' }],
    controllers: [{ name: 'InspectionController', path: 'controllers/inspection.controller' }],
  },

  config_schema: [
    {
      key: 'default_cycle_days',
      name: '默认巡检周期(天)',
      type: 'number',
      default: 30,
      min: 1,
      max: 365,
      description: '生成巡检任务的默认周期',
    },
    {
      key: 'expiring_alert_days',
      name: '到期提醒天数',
      type: 'number',
      default: 3,
      min: 1,
      max: 30,
      description: '巡检任务到期前提醒天数',
    },
    {
      key: 'require_review',
      name: '需要复核',
      type: 'boolean',
      default: true,
      description: '巡检记录单是否需要复核人确认',
    },
  ],

  default_config: {
    default_cycle_days: 30,
    expiring_alert_days: 3,
    require_review: true,
  },
};
