module.exports = {
  id: 'depreciation-management',
  name: '财务管理',
  version: '1.0.0',
  description: '财务管理模块，提供资产折旧测算、预算管理、收支记录、财务报表等综合财务管理能力。',
  category: '财务管理',
  type: 'system',
  status: 'stable',
  author: 'System Team',
  created_at: '2026-02-13T00:00:00Z',
  updated_at: '2026-02-13T00:00:00Z',

  dependencies: [
    {
      module_id: 'asset-management',
      dependency_type: 'required',
      min_version: '1.0.0',
      max_version: '2.0.0',
    },
    {
      module_id: 'user-management',
      dependency_type: 'required',
      min_version: '1.0.0',
      max_version: '2.0.0',
    },
  ],

  compatibility: [],

  frontend_config: {
    menu_keys: [
      '/depreciation-parent',
      '/depreciation',
      '/depreciation/metrology-costs',
      '/depreciation/quality-costs',
      '/depreciation/other-costs',
      '/asset-depreciation',
    ],
    menu_prefixes: [],
    menu_routes: [
      {
        key: '/depreciation',
        icon: 'DollarOutlined',
        label: '财务管理',
        path: '/depreciation',
        component: 'AssetDepreciation',
        permissions: ['depreciation:read'],
      },
      {
        key: '/depreciation/metrology-costs',
        icon: 'DollarOutlined',
        label: '计量费用',
        path: '/depreciation/metrology-costs',
        component: 'FinanceCategoryCosts',
        permissions: ['depreciation:read'],
      },
      {
        key: '/depreciation/quality-costs',
        icon: 'DollarOutlined',
        label: '质控费用',
        path: '/depreciation/quality-costs',
        component: 'FinanceCategoryCosts',
        permissions: ['depreciation:read'],
      },
      {
        key: '/depreciation/other-costs',
        icon: 'DollarOutlined',
        label: '其他费用',
        path: '/depreciation/other-costs',
        component: 'FinanceCategoryCosts',
        permissions: ['depreciation:read'],
      },
    ],
    components: [
      {
        name: 'AssetDepreciation',
        path: 'pages/AssetDepreciation',
        export: 'default',
      },
      {
        name: 'FinanceCategoryCosts',
        path: 'pages/FinanceCategoryCosts',
        export: 'default',
      },
    ],
    permissions: ['depreciation:read', 'depreciation:summary:read', 'depreciation:export'],
  },

  backend_config: {
    api_endpoints: [
      {
        method: 'GET',
        path: '/api/depreciation',
        handler: 'getDepreciationList',
        permissions: ['depreciation:read'],
      },
      {
        method: 'GET',
        path: '/api/depreciation/:id',
        handler: 'getDepreciationDetail',
        permissions: ['depreciation:read'],
      },
      {
        method: 'GET',
        path: '/api/depreciation/summary/by-department',
        handler: 'getSummaryByDepartment',
        permissions: ['depreciation:summary:read'],
      },
      {
        method: 'GET',
        path: '/api/depreciation/summary/by-type',
        handler: 'getSummaryByType',
        permissions: ['depreciation:summary:read'],
      },
      {
        method: 'GET',
        path: '/api/depreciation/summary/by-month',
        handler: 'getSummaryByMonth',
        permissions: ['depreciation:summary:read'],
      },
      {
        method: 'GET',
        path: '/api/depreciation/export',
        handler: 'exportDepreciationReport',
        permissions: ['depreciation:export'],
      },
      {
        method: 'GET',
        path: '/api/asset-depreciation',
        handler: 'getDepreciationListLegacy',
        permissions: ['depreciation:read'],
      },
    ],
    database_tables: ['assets'],
    services: [
      {
        name: 'DepreciationService',
        path: 'services/depreciation.service',
      },
    ],
    permissions: ['depreciation:read', 'depreciation:summary:read', 'depreciation:export'],
  },

  config_schema: [
    {
      key: 'default_method',
      name: '默认折旧方法',
      type: 'select',
      required: false,
      default: 'straight-line',
      group: '基础设置',
      description: '新增资产默认折旧方法。符合《企业会计准则第4号—固定资产》。',
      options: [
        { label: '年限平均法（直线法）', value: 'straight-line', description: '最常用，适用于一般固定资产' },
        { label: '双倍余额递减法', value: 'double-declining', description: '加速折旧法，后期需转换为直线法' },
        { label: '年数总和法', value: 'sum-of-years-digits', description: '加速折旧法，按剩余年限比例计提' },
        { label: '工作量法', value: 'units-of-production', description: '按实际工作量计提' },
        { label: '不计提折旧', value: 'none', description: '土地或已提足折旧的资产' },
      ],
    },
    {
      key: 'default_residual_rate',
      name: '默认残值率',
      type: 'number',
      required: false,
      default: 0.05,
      group: '基础设置',
      description: '资产默认残值率（5%为一般固定资产常用值）。',
      validation: {
        min: 0,
        max: 0.5,
      },
    },
    {
      key: 'include_disposed_assets',
      name: '统计包含已处置资产',
      type: 'boolean',
      required: false,
      default: false,
      group: '流程设置',
      description: '折旧统计是否包含已处置资产。',
    },
    {
      key: 'depreciation_start_rule',
      name: '折旧开始规则',
      type: 'select',
      required: false,
      default: 'next_month',
      group: '流程设置',
      description: '资产入账后折旧开始时点。',
      options: [
        { label: '次月开始（当月不提）', value: 'next_month', description: '符合会计准则的常规做法' },
        { label: '当月开始（入账当月计提）', value: 'current_month', description: '部分行业或特殊情况适用' },
      ],
    },
    {
      key: 'auto_generate_monthly_report',
      name: '自动生成月报',
      type: 'boolean',
      required: false,
      default: true,
      group: '流程设置',
      description: '每月自动生成折旧汇总报表，便于财务核对。',
    },
    {
      key: 'max_export_rows',
      name: '最大导出行数',
      type: 'number',
      required: false,
      default: 5000,
      group: '数据与性能',
      description: '单次导出的最大数据行数。',
      validation: {
        min: 100,
        max: 100000,
      },
    },
    {
      key: 'accounting_standard',
      name: '适用的会计制度',
      type: 'select',
      required: false,
      default: 'enterprise',
      group: '会计制度',
      description: '选择适用的会计制度，不同制度可能有不同的折旧规定。',
      options: [
        { label: '企业会计准则', value: 'enterprise', description: '《企业会计准则》及《企业会计制度》' },
        { label: '医院会计制度', value: 'hospital', description: '《医院会计制度》- 适用于公立医院' },
        { label: '政府会计制度', value: 'government', description: '《政府会计制度》- 适用于行政事业单位' },
      ],
    },
  ],
  default_config: {
    default_method: 'straight-line',
    default_residual_rate: 0.05,
    include_disposed_assets: false,
    depreciation_start_rule: 'next_month',
    auto_generate_monthly_report: true,
    max_export_rows: 5000,
    accounting_standard: 'enterprise',
  },

  interfaces: [
    {
      path: '/api/depreciation',
      method: 'GET',
      description: '获取资产折旧列表与汇总',
    },
    {
      path: '/api/depreciation/summary/by-department',
      method: 'GET',
      description: '按部门汇总折旧数据',
    },
    {
      path: '/api/depreciation/export',
      method: 'GET',
      description: '导出折旧报表',
    },
  ],
};
