module.exports = {
  id: 'asset-management',
  name: '库存管理',
  version: '1.0.0',
  description: '提供完整的库存管理功能，包括资产入库、使用、维护、调拨、报废等全生命周期管理。',
  category: '资产生命周期',
  type: 'system',
  status: 'stable',
  author: 'System Team',
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-15T00:00:00Z',

  dependencies: [
    {
      module_id: 'user-management',
      dependency_type: 'required',
      min_version: '1.0.0',
      max_version: '2.0.0',
    },
    {
      module_id: 'department-management',
      dependency_type: 'optional',
      min_version: '1.0.0',
    },
  ],

  compatibility: [],

  frontend_config: {
    menu_keys: [
      '/assets-parent',
      '/assets',
      '/assets/new',
      '/assets/categories',
      '/assets/locations',
      '/transfer-parent',
      '/transfer',
      '/transfer/new',
      '/transfer/requests',
      '/idle',
    ],
    menu_routes: [
      {
        key: '/assets',
        icon: 'AppstoreOutlined',
        label: '库存管理',
        path: '/assets',
        component: 'AssetList',
        permissions: ['asset:read'],
      },
      {
        key: '/assets/new',
        icon: 'PlusOutlined',
        label: '新增资产',
        path: '/assets/new',
        component: 'AssetForm',
        permissions: ['asset:create'],
        parent: '/assets',
      },
      {
        key: '/assets/categories',
        icon: 'FolderOutlined',
        label: '资产分类',
        path: '/assets/categories',
        component: 'AssetCategorySelect',
        permissions: ['asset:category:read'],
      },
      {
        key: '/assets/locations',
        icon: 'EnvironmentOutlined',
        label: '资产位置',
        path: '/assets/locations',
        component: 'AssetLocationMap',
        permissions: ['asset:location:read'],
      },
    ],
    components: [
      {
        name: 'AssetList',
        path: 'pages/AssetList',
        export: 'default',
      },
      {
        name: 'AssetForm',
        path: 'pages/AssetForm',
        export: 'default',
      },
      {
        name: 'AssetDetail',
        path: 'pages/AssetDetail',
        export: 'default',
      },
      {
        name: 'AssetCategorySelect',
        path: 'pages/AssetCategorySelect',
        export: 'default',
      },
      {
        name: 'AssetLocationMap',
        path: 'pages/AssetLocationMap',
        export: 'default',
      },
    ],
    permissions: [
      'asset:read',
      'asset:create',
      'asset:update',
      'asset:delete',
      'asset:category:read',
      'asset:category:create',
      'asset:category:update',
      'asset:category:delete',
      'asset:location:read',
      'asset:location:update',
    ],
  },

  backend_config: {
    api_endpoints: [
      {
        method: 'GET',
        path: '/api/assets',
        handler: 'getAssets',
        permissions: ['asset:read'],
      },
      {
        method: 'POST',
        path: '/api/assets',
        handler: 'createAsset',
        permissions: ['asset:create'],
      },
      {
        method: 'PUT',
        path: '/api/assets/:id',
        handler: 'updateAsset',
        permissions: ['asset:update'],
      },
      {
        method: 'DELETE',
        path: '/api/assets/:id',
        handler: 'deleteAsset',
        permissions: ['asset:delete'],
      },
      {
        method: 'GET',
        path: '/api/assets/categories',
        handler: 'getAssetCategories',
        permissions: ['asset:category:read'],
      },
      {
        method: 'POST',
        path: '/api/assets/categories',
        handler: 'createAssetCategory',
        permissions: ['asset:category:create'],
      },
      {
        method: 'PUT',
        path: '/api/assets/categories/:id',
        handler: 'updateAssetCategory',
        permissions: ['asset:category:update'],
      },
      {
        method: 'DELETE',
        path: '/api/assets/categories/:id',
        handler: 'deleteAssetCategory',
        permissions: ['asset:category:delete'],
      },
      {
        method: 'GET',
        path: '/api/assets/locations',
        handler: 'getAssetLocations',
        permissions: ['asset:location:read'],
      },
      {
        method: 'POST',
        path: '/api/assets/locations',
        handler: 'updateAssetLocation',
        permissions: ['asset:location:update'],
      },
    ],
    database_tables: [
      'assets',
      'asset_categories',
      'asset_locations',
      'asset_images',
    ],
    services: [
      {
        name: 'AssetService',
        path: 'services/asset.service',
      },
      {
        name: 'AssetCategoryService',
        path: 'services/asset.category.service',
      },
      {
        name: 'AssetLocationService',
        path: 'services/asset.location.service',
      },
    ],
    controllers: [
      {
        name: 'AssetController',
        path: 'controllers/asset.controller',
      },
    ],
    permissions: [
      'asset:read',
      'asset:create',
      'asset:update',
      'asset:delete',
      'asset:category:read',
      'asset:category:create',
      'asset:category:update',
      'asset:category:delete',
      'asset:location:read',
      'asset:location:update',
    ],
  },

  config_schema: [
    {
      key: 'enable_auto_numbering',
      name: '启用自动编号',
      type: 'boolean',
      required: false,
      default: true,
      description: '是否启用资产自动编号功能',
    },
    {
      key: 'number_prefix',
      name: '编号前缀',
      type: 'string',
      required: false,
      default: 'ASSET',
      description: '资产编号的前缀',
      validation: {
        pattern: '^[A-Z]{2,10}$',
        message: '前缀必须为2-10个大写字母',
      },
    },
    {
      key: 'enable_location_tracking',
      name: '启用位置跟踪',
      type: 'boolean',
      required: false,
      default: true,
      description: '是否启用资产位置跟踪功能',
    },
    {
      key: 'enable_image_upload',
      name: '启用图片上传',
      type: 'boolean',
      required: false,
      default: true,
      description: '是否启用资产图片上传功能',
    },
    {
      key: 'max_image_size',
      name: '最大图片大小',
      type: 'number',
      required: false,
      default: 5,
      description: '资产图片的最大大小（MB）',
      validation: {
        min: 1,
        max: 20,
      },
    },
    {
      key: 'enable_asset_approval',
      name: '启用资产审批',
      type: 'boolean',
      required: false,
      default: true,
      description: '是否启用资产创建和修改的审批流程',
    },
    {
      key: 'max_assets_per_page',
      name: '每页最大资产数',
      type: 'number',
      required: false,
      default: 50,
      description: '资产列表每页显示的最大数量',
      validation: {
        min: 10,
        max: 200,
      },
    },
  ],
  default_config: {
    enable_auto_numbering: true,
    number_prefix: 'ASSET',
    enable_location_tracking: true,
    enable_image_upload: true,
    max_image_size: 5,
    enable_asset_approval: true,
    max_assets_per_page: 50,
  },

  interfaces: [
    {
      name: 'IAssetService',
      type: 'service',
      methods: [
        {
          name: 'getAssetById',
          input: { id: 'number' },
          output: 'Asset',
          description: '根据ID获取资产',
        },
        {
          name: 'getAssetByCode',
          input: { code: 'string' },
          output: 'Asset',
          description: '根据编码获取资产',
        },
        {
          name: 'createAsset',
          input: { data: 'AssetData' },
          output: 'Asset',
          description: '创建资产',
        },
        {
          name: 'updateAsset',
          input: { id: 'number', data: 'AssetData' },
          output: 'Asset',
          description: '更新资产',
        },
        {
          name: 'deleteAsset',
          input: { id: 'number' },
          output: 'boolean',
          description: '删除资产',
        },
      ],
    },
    {
      name: 'IAssetCategoryService',
      type: 'service',
      methods: [
        {
          name: 'getCategoryTree',
          input: {},
          output: 'CategoryTree[]',
          description: '获取分类树',
        },
        {
          name: 'createCategory',
          input: { data: 'CategoryData' },
          output: 'Category',
          description: '创建分类',
        },
      ],
    },
    {
      name: 'IAssetLocationService',
      type: 'service',
      methods: [
        {
          name: 'getAssetLocation',
          input: { assetCode: 'string' },
          output: 'Location',
          description: '获取资产位置',
        },
        {
          name: 'updateAssetLocation',
          input: { assetCode: 'string', location: 'LocationData' },
          output: 'Location',
          description: '更新资产位置',
        },
        {
          name: 'getAssetsInArea',
          input: { area: 'AreaData' },
          output: 'Asset[]',
          description: '获取指定区域内的资产',
        },
      ],
    },
  ],
};
