module.exports = {
  id: 'quality-control',
  name: '计量管理',
  version: '1.1.0',
  description: '计量管理模块，支持计量器具台账、检定校准、报告识别与到期提醒。',
  category: '质量与安全',
  type: 'system',
  status: 'stable',
  author: 'System Team',
  created_at: '2026-01-29T00:00:00Z',
  updated_at: '2026-02-23T00:00:00Z',

  dependencies: [
    {
      module_id: 'quality-common',
      dependency_type: 'required',
      min_version: '1.0.0',
      max_version: '2.0.0',
      interfaces: ['IUserProvider'],
      interface_source: 'user-management',
    },
    {
      module_id: 'asset-management',
      dependency_type: 'required',
      min_version: '1.0.0',
      max_version: '2.0.0',
      interfaces: ['IAssetProvider'],
      interface_source: 'shared',
    },
  ],

  compatibility: {
    min_node_version: '14.0.0',
    max_node_version: '24.0.0',
    supported_databases: ['mysql'],
    browser_compatibility: {
      chrome: '>=80',
      firefox: '>=75',
      safari: '>=13',
      edge: '>=80',
    },
  },

  frontend_config: {
    menu_keys: [
      '/quality-control/metrology',
      '/quality-control/metrology/upload',
    ],
    menu_prefixes: ['/quality-control/metrology'],
    menu_routes: [
      {
        key: '/quality-control/metrology',
        icon: 'ToolOutlined',
        label: '计量管理',
        path: '/quality-control/metrology',
        component: 'MetrologyList',
        permissions: ['quality-control:metrology:read'],
      },
      {
        key: '/quality-control/metrology/new',
        icon: 'PlusOutlined',
        label: '新增计量器具',
        path: '/quality-control/metrology/new',
        component: 'MetrologyForm',
        permissions: ['quality-control:metrology:create'],
        parent: '/quality-control/metrology',
      },
      {
        key: '/quality-control/metrology/edit/:id',
        icon: 'EditOutlined',
        label: '编辑计量器具',
        path: '/quality-control/metrology/edit/:id',
        component: 'MetrologyForm',
        permissions: ['quality-control:metrology:update'],
        parent: '/quality-control/metrology',
      },
      {
        key: '/quality-control/metrology/:id',
        icon: 'EyeOutlined',
        label: '计量器具详情',
        path: '/quality-control/metrology/:id',
        component: 'MetrologyDetail',
        permissions: ['quality-control:metrology:read'],
        parent: '/quality-control/metrology',
      },
      {
        key: '/quality-control/metrology/upload',
        icon: 'UploadOutlined',
        label: '报告智能识别',
        path: '/quality-control/metrology/upload',
        component: 'MetrologyUploadPage',
        permissions: ['quality-control:metrology:update'],
        parent: '/quality-control/metrology',
      },
    ],
    components: [
      { name: 'MetrologyList', path: 'pages/MetrologyList', export: 'default' },
      { name: 'MetrologyForm', path: 'pages/MetrologyForm', export: 'default' },
      { name: 'MetrologyDetail', path: 'pages/MetrologyDetail', export: 'default' },
      { name: 'MetrologyUploadPage', path: 'pages/quality-control/MetrologyUploadPage', export: 'default' },
    ],
    permissions: [
      'quality-control:metrology:read',
      'quality-control:metrology:create',
      'quality-control:metrology:update',
      'quality-control:metrology:delete',
    ],
  },

  backend_config: {
    api_endpoints: [
      // 计量管理相关
      { method: 'GET', path: '/api/quality-control/metrology', handler: 'getMetrologyList', permissions: ['quality-control:metrology:read'] },
      { method: 'GET', path: '/api/quality-control/metrology/:id', handler: 'getMetrologyById', permissions: ['quality-control:metrology:read'] },
      { method: 'POST', path: '/api/quality-control/metrology', handler: 'createMetrology', permissions: ['quality-control:metrology:create'] },
      { method: 'PUT', path: '/api/quality-control/metrology/:id', handler: 'updateMetrology', permissions: ['quality-control:metrology:update'] },
      { method: 'DELETE', path: '/api/quality-control/metrology/:id', handler: 'deleteMetrology', permissions: ['quality-control:metrology:delete'] },
      { method: 'POST', path: '/api/quality-control/metrology/:id/attachments', handler: 'uploadMetrologyAttachment', permissions: ['quality-control:metrology:update'] },
      { method: 'DELETE', path: '/api/quality-control/metrology/attachments/:id', handler: 'deleteMetrologyAttachment', permissions: ['quality-control:metrology:update'] },
      { method: 'GET', path: '/api/quality-control/metrology/expiring', handler: 'getExpiringMetrology', permissions: ['quality-control:metrology:read'] },
      { method: 'GET', path: '/api/quality-control/metrology/statistics', handler: 'getMetrologyStatistics', permissions: ['quality-control:metrology:read'] },
      { method: 'POST', path: '/api/quality-control/metrology/analyze-report', handler: 'analyzeMetrologyReport', permissions: ['quality-control:metrology:update'] },
      { method: 'POST', path: '/api/quality-control/metrology/from-file', handler: 'createMetrologyFromFile', permissions: ['quality-control:metrology:create'] },
      { method: 'GET', path: '/api/quality-control/reports/metrology', handler: 'getMetrologyReport', permissions: ['quality-control:metrology:read'] },
      // 质量控制记录相关
      { method: 'GET', path: '/api/quality-control', handler: 'getQualityControlRecords', permissions: ['quality-control:qc:read'] },
      { method: 'GET', path: '/api/quality-control/quality-control', handler: 'getQualityControlRecords', permissions: ['quality-control:qc:read'] },
      { method: 'GET', path: '/api/quality-control/statistics', handler: 'getQualityControlStatistics', permissions: ['quality-control:qc:read'] },
      { method: 'GET', path: '/api/quality-control/quality-control/statistics', handler: 'getQualityControlStatistics', permissions: ['quality-control:qc:read'] },
      { method: 'GET', path: '/api/quality-control/statistics/advanced', handler: 'getAdvancedQualityControlStatistics', permissions: ['quality-control:qc:read'] },
      { method: 'GET', path: '/api/quality-control/quality-control/statistics/advanced', handler: 'getAdvancedQualityControlStatistics', permissions: ['quality-control:qc:read'] },
      { method: 'GET', path: '/api/quality-control/expiring', handler: 'getExpiringQualityControlRecords', permissions: ['quality-control:qc:read'] },
      { method: 'GET', path: '/api/quality-control/quality-control/expiring', handler: 'getExpiringQualityControlRecords', permissions: ['quality-control:qc:read'] },
      { method: 'GET', path: '/api/quality-control/:id', handler: 'getQualityControlRecordById', permissions: ['quality-control:qc:read'] },
      { method: 'GET', path: '/api/quality-control/quality-control/:id', handler: 'getQualityControlRecordById', permissions: ['quality-control:qc:read'] },
      { method: 'POST', path: '/api/quality-control', handler: 'createQualityControlRecord', permissions: ['quality-control:qc:create'] },
      { method: 'POST', path: '/api/quality-control/quality-control', handler: 'createQualityControlRecord', permissions: ['quality-control:qc:create'] },
      { method: 'PUT', path: '/api/quality-control/:id', handler: 'updateQualityControlRecord', permissions: ['quality-control:qc:update'] },
      { method: 'PUT', path: '/api/quality-control/quality-control/:id', handler: 'updateQualityControlRecord', permissions: ['quality-control:qc:update'] },
      { method: 'DELETE', path: '/api/quality-control/:id', handler: 'deleteQualityControlRecord', permissions: ['quality-control:qc:delete'] },
      { method: 'DELETE', path: '/api/quality-control/quality-control/:id', handler: 'deleteQualityControlRecord', permissions: ['quality-control:qc:delete'] },
      { method: 'GET', path: '/api/quality-control/asset/:assetCode/history', handler: 'getAssetQualityHistory', permissions: ['quality-control:qc:read'] },
    ],
    database_tables: ['metrology_records', 'metrology_attachments', 'quality_control_records'],
    services: [
      { name: 'MetrologyService', path: 'services/metrology.service' },
      { name: 'QualityControlService', path: 'services/quality-control.service' },
    ],
    permissions: [
      'quality-control:metrology:read',
      'quality-control:metrology:create',
      'quality-control:metrology:update',
      'quality-control:metrology:delete',
      'quality-control:qc:read',
      'quality-control:qc:create',
      'quality-control:qc:update',
      'quality-control:qc:delete',
    ],
  },

  config_schema: [
    {
      key: 'enable_metrology_management',
      name: '启用计量管理',
      type: 'boolean',
      required: false,
      default: true,
      description: '是否启用计量器具管理功能',
    },
    {
      key: 'metrology_calibration_days',
      name: '计量校准提前提醒天数',
      type: 'number',
      required: false,
      default: 30,
      description: '计量器具校准的提前提醒天数',
      validation: { min: 1, max: 90 },
    },
    {
      key: 'max_records_per_page',
      name: '每页最大记录数',
      type: 'number',
      required: false,
      default: 50,
      description: '列表页面每页显示的最大记录数',
      validation: { min: 10, max: 200 },
    },
  ],

  default_config: {
    enable_metrology_management: true,
    metrology_calibration_days: 30,
    max_records_per_page: 50,
  },

  interfaces: [],
};
