module.exports = {
  id: 'preventive-maintenance-management',
  name: '预防性维护',
  version: '1.0.0',
  description: '预防性维护模块，支持维护计划、模板、提醒与效率分析。',
  category: '维护与工单',
  type: 'system',
  status: 'stable',
  author: 'System Team',
  created_at: '2026-02-23T00:00:00Z',
  updated_at: '2026-02-23T00:00:00Z',

  dependencies: [
    {
      module_id: 'asset-management',
      dependency_type: 'required',
      min_version: '1.0.0',
      max_version: '2.0.0',
    },
    {
      module_id: 'user-management',
      dependency_type: 'required',
      min_version: '1.0.0',
      max_version: '2.0.0',
    },
  ],

  compatibility: [],

  frontend_config: {
    menu_keys: [
      '/maintenance/plans',
      '/maintenance/templates',
      '/maintenance/reminders',
      '/maintenance/efficiency',
    ],
    menu_prefixes: [
      '/maintenance/plans',
      '/maintenance/templates',
      '/maintenance/reminders',
      '/maintenance/efficiency',
    ],
    menu_routes: [
      {
        key: '/maintenance/plans',
        icon: 'CalendarOutlined',
        label: '预防性维护',
        path: '/maintenance/plans',
        component: 'PreventiveMaintenanceList',
        permissions: ['maintenance:plan:read'],
      },
      {
        key: '/maintenance/plans/new',
        icon: 'PlusOutlined',
        label: '新增维护计划',
        path: '/maintenance/plans/new',
        component: 'PreventiveMaintenanceForm',
        permissions: ['maintenance:plan:create'],
        parent: '/maintenance/plans',
      },
      {
        key: '/maintenance/templates',
        icon: 'FileTextOutlined',
        label: '维护计划模板',
        path: '/maintenance/templates',
        component: 'MaintenanceTemplateList',
        permissions: ['maintenance:template:read'],
        parent: '/maintenance/plans',
      },
      {
        key: '/maintenance/reminders',
        icon: 'BellOutlined',
        label: '维护提醒管理',
        path: '/maintenance/reminders',
        component: 'MaintenanceReminderList',
        permissions: ['maintenance:reminder:read'],
        parent: '/maintenance/plans',
      },
      {
        key: '/maintenance/efficiency',
        icon: 'LineChartOutlined',
        label: '维护效率分析',
        path: '/maintenance/efficiency',
        component: 'MaintenanceEfficiencyDashboard',
        permissions: ['maintenance:efficiency:read'],
        parent: '/maintenance/plans',
      },
    ],
    components: [
      { name: 'PreventiveMaintenanceList', path: 'pages/PreventiveMaintenanceList', export: 'default' },
      { name: 'PreventiveMaintenanceForm', path: 'pages/PreventiveMaintenanceForm', export: 'default' },
      { name: 'PreventiveMaintenanceDetail', path: 'pages/PreventiveMaintenanceDetail', export: 'default' },
      { name: 'MaintenanceTemplateList', path: 'pages/MaintenanceTemplateList', export: 'default' },
      { name: 'MaintenanceTemplateForm', path: 'pages/MaintenanceTemplateForm', export: 'default' },
      { name: 'MaintenanceReminderList', path: 'pages/MaintenanceReminderList', export: 'default' },
      { name: 'MaintenanceEfficiencyDashboard', path: 'pages/MaintenanceEfficiencyDashboard', export: 'default' },
    ],
    permissions: [
      'maintenance:plan:read',
      'maintenance:plan:create',
      'maintenance:plan:update',
      'maintenance:plan:delete',
      'maintenance:template:read',
      'maintenance:template:create',
      'maintenance:template:update',
      'maintenance:template:delete',
      'maintenance:reminder:read',
      'maintenance:reminder:create',
      'maintenance:reminder:update',
      'maintenance:reminder:delete',
      'maintenance:efficiency:read',
    ],
  },

  backend_config: {
    api_endpoints: [
      { method: 'GET', path: '/api/maintenance/plans', handler: 'getMaintenancePlans', permissions: ['maintenance:plan:read'] },
      { method: 'POST', path: '/api/maintenance/plans', handler: 'createMaintenancePlan', permissions: ['maintenance:plan:create'] },
      { method: 'GET', path: '/api/maintenance/plans/:id', handler: 'getMaintenancePlan', permissions: ['maintenance:plan:read'] },
      { method: 'PUT', path: '/api/maintenance/plans/:id', handler: 'updateMaintenancePlan', permissions: ['maintenance:plan:update'] },
      { method: 'POST', path: '/api/maintenance/plans/:id/complete', handler: 'completeMaintenancePlan', permissions: ['maintenance:plan:update'] },
      { method: 'GET', path: '/api/maintenance/plans/:id/history', handler: 'getMaintenancePlanHistory', permissions: ['maintenance:plan:read'] },
      { method: 'DELETE', path: '/api/maintenance/plans/:id', handler: 'deleteMaintenancePlan', permissions: ['maintenance:plan:delete'] },
      { method: 'GET', path: '/api/maintenance/templates', handler: 'getMaintenanceTemplates', permissions: ['maintenance:template:read'] },
      { method: 'POST', path: '/api/maintenance/templates', handler: 'createMaintenanceTemplate', permissions: ['maintenance:template:create'] },
      { method: 'PUT', path: '/api/maintenance/templates/:id', handler: 'updateMaintenanceTemplate', permissions: ['maintenance:template:update'] },
      { method: 'DELETE', path: '/api/maintenance/templates/:id', handler: 'deleteMaintenanceTemplate', permissions: ['maintenance:template:delete'] },
      { method: 'GET', path: '/api/maintenance/reminders', handler: 'getMaintenanceReminders', permissions: ['maintenance:reminder:read'] },
      { method: 'POST', path: '/api/maintenance/reminders/send', handler: 'sendMaintenanceReminder', permissions: ['maintenance:reminder:create'] },
      { method: 'POST', path: '/api/maintenance/reminders/config', handler: 'configMaintenanceReminder', permissions: ['maintenance:reminder:update'] },
      { method: 'GET', path: '/api/maintenance/efficiency/overview', handler: 'getEfficiencyOverview', permissions: ['maintenance:efficiency:read'] },
    ],
    database_tables: [
      'preventive_maintenance_plans',
      'maintenance_plan_history',
      'maintenance_templates',
      'maintenance_template_items',
      'maintenance_reminders',
    ],
    services: [
      { name: 'PreventiveMaintenanceService', path: 'services/preventive-maintenance.service' },
    ],
    permissions: [
      'maintenance:plan:read',
      'maintenance:plan:create',
      'maintenance:plan:update',
      'maintenance:plan:delete',
      'maintenance:template:read',
      'maintenance:template:create',
      'maintenance:template:update',
      'maintenance:template:delete',
      'maintenance:reminder:read',
      'maintenance:reminder:create',
      'maintenance:reminder:update',
      'maintenance:reminder:delete',
      'maintenance:efficiency:read',
    ],
  },

  config_schema: [
    {
      key: 'enable_preventive_maintenance',
      name: '启用预防性维护',
      type: 'boolean',
      required: false,
      default: true,
      description: '是否启用预防性维护功能',
    },
    {
      key: 'default_cycle_days',
      name: '默认维护周期(天)',
      type: 'number',
      required: false,
      default: 30,
      description: '未指定计划周期时采用的默认值',
      validation: { min: 1, max: 365 },
    },
    {
      key: 'enable_auto_reminders',
      name: '启用自动提醒',
      type: 'boolean',
      required: false,
      default: true,
      description: '是否启用预防性维护自动提醒',
    },
    {
      key: 'reminder_advance_days',
      name: '提醒提前天数',
      type: 'number',
      required: false,
      default: 3,
      description: '预防性维护计划到期前多少天发送提醒',
      validation: { min: 1, max: 30 },
    },
    {
      key: 'enable_efficiency_analysis',
      name: '启用效率分析',
      type: 'boolean',
      required: false,
      default: true,
      description: '是否启用预防性维护效率分析功能',
    },
  ],
  default_config: {
    enable_preventive_maintenance: true,
    default_cycle_days: 30,
    enable_auto_reminders: true,
    reminder_advance_days: 3,
    enable_efficiency_analysis: true,
  },
};
