module.exports = {
  id: 'maintenance-management',
  name: '日常维修',
  version: '1.0.0',
  description:
    '提供维修日志、维修工单、维修申请等日常维修能力。',
  category: '维护与工单',
  type: 'system',
  status: 'stable',
  author: 'System Team',
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-15T00:00:00Z',

  dependencies: [
    {
      module_id: 'asset-management',
      dependency_type: 'required',
      min_version: '1.0.0',
      max_version: '2.0.0',
    },
    {
      module_id: 'user-management',
      dependency_type: 'required',
      min_version: '1.0.0',
      max_version: '2.0.0',
    },
    {
      module_id: 'department-management',
      dependency_type: 'optional',
      min_version: '1.0.0',
    },
  ],

  compatibility: [],

  frontend_config: {
    menu_keys: [
      '/maintenance/logs',
      '/maintenance/logs/new',
      '/maintenance/workorders',
      '/maintenance/requests',
      '/maintenance/costs',
    ],
    menu_prefixes: ['/maintenance/logs', '/maintenance/workorders', '/maintenance/requests', '/maintenance/costs'],
    menu_routes: [
      {
        key: '/maintenance/logs',
        icon: 'ToolOutlined',
        label: '维护日志',
        path: '/maintenance/logs',
        component: 'MaintenanceLogList',
        permissions: ['maintenance:log:read'],
      },
      {
        key: '/maintenance/logs/new',
        icon: 'PlusOutlined',
        label: '新增维护日志',
        path: '/maintenance/logs/new',
        component: 'MaintenanceLogForm',
        permissions: ['maintenance:log:create'],
        parent: '/maintenance/logs',
      },
      {
        key: '/maintenance/workorders',
        icon: 'OrderedListOutlined',
        label: '维修工单',
        path: '/maintenance/workorders',
        component: 'MaintenanceWorkOrderList',
        permissions: ['maintenance:workorder:read'],
      },
      {
        key: '/maintenance/requests',
        icon: 'MessageOutlined',
        label: '维修申请',
        path: '/maintenance/requests',
        component: 'MaintenanceRequestList',
        permissions: ['maintenance:request:read'],
      },
      {
        key: '/maintenance/costs',
        icon: 'DollarOutlined',
        label: '维护费用管理',
        path: '/maintenance/costs',
        component: 'MaintenanceCostManagement',
        permissions: ['maintenance:cost:read'],
      },
    ],
    components: [
      {
        name: 'MaintenanceLogList',
        path: 'pages/MaintenanceLogList',
        export: 'default',
      },
      {
        name: 'MaintenanceLogForm',
        path: 'pages/MaintenanceLogForm',
        export: 'default',
      },
      {
        name: 'MaintenanceWorkOrderList',
        path: 'pages/MaintenanceWorkOrderList',
        export: 'default',
      },
      {
        name: 'MaintenanceRequestList',
        path: 'pages/MaintenanceRequestList',
        export: 'default',
      },
      {
        name: 'MaintenanceCostManagement',
        path: 'pages/MaintenanceCostManagement',
        export: 'default',
      },
    ],
    permissions: [
      'maintenance:log:read',
      'maintenance:log:create',
      'maintenance:log:update',
      'maintenance:log:delete',
      'maintenance:workorder:read',
      'maintenance:workorder:create',
      'maintenance:workorder:update',
      'maintenance:workorder:delete',
      'maintenance:request:read',
      'maintenance:request:create',
      'maintenance:request:update',
      'maintenance:request:delete',
      'maintenance:cost:read',
      'maintenance:cost:create',
      'maintenance:cost:update',
      'maintenance:cost:delete',
    ],
  },

  backend_config: {
    api_endpoints: [
      {
        method: 'GET',
        path: '/api/maintenance/logs',
        handler: 'getMaintenanceLogs',
        permissions: ['maintenance:log:read'],
      },
      {
        method: 'POST',
        path: '/api/maintenance/logs',
        handler: 'createMaintenanceLog',
        permissions: ['maintenance:log:create'],
      },
      {
        method: 'PUT',
        path: '/api/maintenance/logs/:id',
        handler: 'updateMaintenanceLog',
        permissions: ['maintenance:log:update'],
      },
      {
        method: 'DELETE',
        path: '/api/maintenance/logs/:id',
        handler: 'deleteMaintenanceLog',
        permissions: ['maintenance:log:delete'],
      },
      {
        method: 'GET',
        path: '/api/maintenance/workorders',
        handler: 'getMaintenanceWorkOrders',
        permissions: ['maintenance:workorder:read'],
      },
      {
        method: 'POST',
        path: '/api/maintenance/workorders',
        handler: 'createMaintenanceWorkOrder',
        permissions: ['maintenance:workorder:create'],
      },
      {
        method: 'PUT',
        path: '/api/maintenance/workorders/:id',
        handler: 'updateMaintenanceWorkOrder',
        permissions: ['maintenance:workorder:update'],
      },
      {
        method: 'DELETE',
        path: '/api/maintenance/workorders/:id',
        handler: 'deleteMaintenanceWorkOrder',
        permissions: ['maintenance:workorder:delete'],
      },
      {
        method: 'GET',
        path: '/api/maintenance/requests',
        handler: 'getMaintenanceRequests',
        permissions: ['maintenance:request:read'],
      },
      {
        method: 'POST',
        path: '/api/maintenance/requests',
        handler: 'createMaintenanceRequest',
        permissions: ['maintenance:request:create'],
      },
      {
        method: 'PUT',
        path: '/api/maintenance/requests/:id',
        handler: 'updateMaintenanceRequest',
        permissions: ['maintenance:request:update'],
      },
      {
        method: 'DELETE',
        path: '/api/maintenance/requests/:id',
        handler: 'deleteMaintenanceRequest',
        permissions: ['maintenance:request:delete'],
      },
      {
        method: 'GET',
        path: '/api/maintenance/costs',
        handler: 'getCosts',
        permissions: ['maintenance:cost:read'],
      },
      {
        method: 'POST',
        path: '/api/maintenance/costs',
        handler: 'createCost',
        permissions: ['maintenance:cost:create'],
      },
      {
        method: 'PUT',
        path: '/api/maintenance/costs/:id',
        handler: 'updateCost',
        permissions: ['maintenance:cost:update'],
      },
      {
        method: 'DELETE',
        path: '/api/maintenance/costs/:id',
        handler: 'deleteCost',
        permissions: ['maintenance:cost:delete'],
      },
      {
        method: 'GET',
        path: '/api/maintenance/costs/trend',
        handler: 'getCostTrend',
        permissions: ['maintenance:cost:read'],
      },
      {
        method: 'GET',
        path: '/api/maintenance/costs/department',
        handler: 'getCostDepartment',
        permissions: ['maintenance:cost:read'],
      },
      {
        method: 'GET',
        path: '/api/maintenance/costs/asset-type',
        handler: 'getCostAssetType',
        permissions: ['maintenance:cost:read'],
      },
      {
        method: 'GET',
        path: '/api/maintenance/costs/maintenance-type',
        handler: 'getCostMaintenanceType',
        permissions: ['maintenance:cost:read'],
      },
      {
        method: 'GET',
        path: '/api/maintenance/costs/high-cost-assets',
        handler: 'getHighCostAssets',
        permissions: ['maintenance:cost:read'],
      },
      {
        method: 'GET',
        path: '/api/maintenance/costs/analysis',
        handler: 'getCostAnalysis',
        permissions: ['maintenance:cost:read'],
      },
    ],
    database_tables: [
      'maintenance_logs',
      'maintenance_log_attachments',
      'maintenance_workorders',
      'maintenance_workorder_materials',
      'maintenance_requests',
      'maintenance_costs',
    ],
    services: [
      {
        name: 'MaintenanceLogService',
        path: 'services/maintenance.log.service',
      },
      {
        name: 'MaintenanceWorkOrderService',
        path: 'services/maintenance.workorder.service',
      },
      {
        name: 'MaintenanceRequestService',
        path: 'services/maintenance.request.service',
      },
      {
        name: 'MaintenanceCostService',
        path: 'services/maintenance/costs.service',
      },
    ],
    permissions: [
      'maintenance:log:read',
      'maintenance:log:create',
      'maintenance:log:update',
      'maintenance:log:delete',
      'maintenance:workorder:read',
      'maintenance:workorder:create',
      'maintenance:workorder:update',
      'maintenance:workorder:delete',
      'maintenance:request:read',
      'maintenance:request:create',
      'maintenance:request:update',
      'maintenance:request:delete',
      'maintenance:cost:read',
      'maintenance:cost:create',
      'maintenance:cost:update',
      'maintenance:cost:delete',
    ],
  },

  config_schema: [
    {
      key: 'max_maintenance_logs_per_page',
      name: '每页最大日志数',
      type: 'number',
      required: false,
      default: 50,
      description: '维护日志列表每页显示的最大数量',
      validation: {
        min: 10,
        max: 200,
      },
    },
    {
      key: 'notification_channels',
      name: '通知渠道',
      type: 'multi_select',
      required: false,
      default: ['system'],
      description: '维护提醒的通知渠道',
      options: [
        { label: '系统通知', value: 'system' },
        { label: '邮件', value: 'email' },
        { label: '短信', value: 'sms' },
      ],
    },
  ],
  default_config: {
    max_maintenance_logs_per_page: 50,
    notification_channels: ['system'],
  },

  interfaces: [
    {
      name: 'IMaintenanceLogService',
      type: 'service',
      methods: [
        {
          name: 'getMaintenanceLogById',
          input: { id: 'number' },
          output: 'MaintenanceLog',
          description: '根据ID获取维护日志',
        },
        {
          name: 'createMaintenanceLog',
          input: { data: 'MaintenanceLogData' },
          output: 'MaintenanceLog',
          description: '创建维护日志',
        },
        {
          name: 'updateMaintenanceLog',
          input: { id: 'number', data: 'MaintenanceLogData' },
          output: 'MaintenanceLog',
          description: '更新维护日志',
        },
        {
          name: 'deleteMaintenanceLog',
          input: { id: 'number' },
          output: 'boolean',
          description: '删除维护日志',
        },
      ],
    },
    {
      name: 'IMaintenanceTemplateService',
      type: 'service',
      methods: [
        {
          name: 'getMaintenanceTemplateById',
          input: { id: 'number' },
          output: 'MaintenanceTemplate',
          description: '根据ID获取维护模板',
        },
        {
          name: 'createMaintenanceTemplate',
          input: { data: 'MaintenanceTemplateData' },
          output: 'MaintenanceTemplate',
          description: '创建维护模板',
        },
        {
          name: 'recommendTemplates',
          input: { assetData: 'AssetData' },
          output: 'MaintenanceTemplate[]',
          description: '根据资产推荐维护模板',
        },
      ],
    },
    {
      name: 'IMaintenanceReminderService',
      type: 'service',
      methods: [
        {
          name: 'checkReminders',
          input: {},
          output: 'Reminder[]',
          description: '检查需要发送的提醒',
        },
        {
          name: 'sendReminder',
          input: { reminderId: 'number' },
          output: 'boolean',
          description: '发送维护提醒',
        },
      ],
    },
    {
      name: 'IMaintenanceEfficiencyService',
      type: 'service',
      methods: [
        {
          name: 'getEfficiencyOverview',
          input: { params: 'EfficiencyParams' },
          output: 'EfficiencyOverview',
          description: '获取效率概览',
        },
        {
          name: 'getResponseTimeAnalysis',
          input: { params: 'ResponseTimeParams' },
          output: 'ResponseTimeData',
          description: '获取响应时间分析',
        },
      ],
    },
  ],
};
