module.exports = {
  id: 'inventory-management',
  name: '盘点管理',
  version: '1.0.0',
  description: '盘点管理模块，聚焦资产盘点、盘点差异处理与盘点执行。',
  category: '资产生命周期',
  type: 'system',
  status: 'stable',
  author: 'System Team',
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2026-02-21T00:00:00Z',

  dependencies: [
    {
      module_id: 'asset-management',
      dependency_type: 'required',
      min_version: '1.0.0',
      max_version: '2.0.0',
    },
    {
      module_id: 'user-management',
      dependency_type: 'required',
      min_version: '1.0.0',
      max_version: '2.0.0',
    },
  ],

  compatibility: [],

  frontend_config: {
    menu_keys: ['/inventory-parent', '/inventory', '/inventory/self'],
    menu_prefixes: ['/inventory'],
    menu_routes: [
      {
        key: '/inventory',
        icon: 'FileSearchOutlined',
        label: '资产盘点',
        path: '/inventory',
        component: 'InventoryList',
        permissions: ['inventory:read'],
      },
      {
        key: '/inventory/self',
        icon: 'FileSearchOutlined',
        label: '我的资产盘点',
        path: '/inventory/self',
        component: 'InventorySelfCheck',
        permissions: ['inventory:read'],
      },
    ],
    components: [
      { name: 'InventoryList', path: 'pages/InventoryList', export: 'default' },
      { name: 'InventorySelfCheck', path: 'pages/InventorySelfCheck', export: 'default' },
      { name: 'InventoryForm', path: 'pages/InventoryForm', export: 'default' },
      { name: 'InventoryDetail', path: 'pages/InventoryDetail', export: 'default' },
      { name: 'InventoryScanner', path: 'pages/InventoryScanner', export: 'default' },
    ],
    permissions: ['inventory:read', 'inventory:create', 'inventory:update', 'inventory:delete'],
  },

  backend_config: {
    api_endpoints: [
      { method: 'GET', path: '/api/inventory', handler: 'listInventory', permissions: ['inventory:read'] },
      { method: 'GET', path: '/api/inventory/statistics', handler: 'getStatistics', permissions: ['inventory:read'] },
      { method: 'POST', path: '/api/inventory', handler: 'createInventory', permissions: ['inventory:create'] },
      { method: 'PUT', path: '/api/inventory/:id', handler: 'updateInventory', permissions: ['inventory:update'] },
      { method: 'DELETE', path: '/api/inventory/:id', handler: 'deleteInventory', permissions: ['inventory:delete'] },
      { method: 'PUT', path: '/api/inventory/:id/status', handler: 'updateStatus', permissions: ['inventory:update'] },
      { method: 'POST', path: '/api/inventory/:id/start', handler: 'startInventory', permissions: ['inventory:update'] },
      { method: 'POST', path: '/api/inventory/:id/complete', handler: 'completeInventory', permissions: ['inventory:update'] },
      { method: 'GET', path: '/api/inventory/:id/statistics', handler: 'getInventoryStatistics', permissions: ['inventory:read'] },
      { method: 'POST', path: '/api/inventory/:id/scan', handler: 'scanAsset', permissions: ['inventory:update'] },
      { method: 'GET', path: '/api/inventory/:id/scan-logs', handler: 'getScanLogs', permissions: ['inventory:read'] },
      { method: 'POST', path: '/api/inventory/:id/details', handler: 'addDetail', permissions: ['inventory:create'] },
      { method: 'POST', path: '/api/inventory/:id/details/batch', handler: 'batchAddDetails', permissions: ['inventory:create'] },
      { method: 'PUT', path: '/api/inventory/:id/details/:detailId', handler: 'updateDetail', permissions: ['inventory:update'] },
      { method: 'DELETE', path: '/api/inventory/:id/details/:detailId', handler: 'deleteDetail', permissions: ['inventory:delete'] },
      { method: 'GET', path: '/api/inventory/self/windows', handler: 'getSelfCheckWindows', permissions: ['inventory:read'] },
      { method: 'GET', path: '/api/inventory/self/assets', handler: 'getMyAssets', permissions: ['inventory:read'] },
      { method: 'POST', path: '/api/inventory/self/confirm', handler: 'confirmSelfCheck', permissions: ['inventory:update'] },
    ],
    database_tables: ['inventory_records', 'inventory_details', 'inventory_scan_logs'],
    controllers: [{ name: 'InventoryController', path: 'controllers/inventory.controller' }],
    services: [{ name: 'InventoryService', path: 'services/inventory.service' }],
    permissions: ['inventory:read', 'inventory:create', 'inventory:update', 'inventory:delete'],
  },

  config_schema: [
    {
      key: 'enable_self_check',
      name: '启用自盘模式',
      type: 'boolean',
      required: false,
      default: true,
      group: '基础设置',
      description: '是否允许员工执行我的资产盘点。',
    },
    {
      key: 'inventory_scan_mode',
      name: '扫码方式',
      type: 'select',
      required: false,
      default: 'hybrid',
      group: '基础设置',
      description: '盘点时的扫码模式。',
      options: [
        { label: '摄像头扫码', value: 'camera' },
        { label: '扫码枪', value: 'scanner' },
        { label: '混合模式', value: 'hybrid' },
      ],
    },
    {
      key: 'auto_close_days',
      name: '盘点任务自动关闭天数',
      type: 'number',
      required: false,
      default: 7,
      group: '流程设置',
      description: '任务超过指定天数未处理时自动关闭。',
      validation: {
        min: 1,
        max: 90,
      },
    },
    {
      key: 'difference_threshold_percent',
      name: '差异预警阈值(%)',
      type: 'number',
      required: false,
      default: 5,
      group: '流程设置',
      description: '盘点差异比例超过阈值时触发预警。',
      validation: {
        min: 0,
        max: 100,
      },
    },
    {
      key: 'max_items_per_batch',
      name: '单批次最大盘点数量',
      type: 'number',
      required: false,
      default: 500,
      group: '数据与性能',
      description: '单次盘点任务允许处理的最大资产条数。',
      validation: {
        min: 50,
        max: 5000,
      },
    },
    {
      key: 'notification_channels',
      name: '通知渠道',
      type: 'multi_select',
      required: false,
      default: ['system'],
      group: '通知设置',
      description: '盘点任务提醒通知渠道。',
      options: [
        { label: '系统通知', value: 'system' },
        { label: '邮件', value: 'email' },
        { label: '短信', value: 'sms' },
      ],
    },
  ],
  default_config: {
    enable_self_check: true,
    inventory_scan_mode: 'hybrid',
    auto_close_days: 7,
    difference_threshold_percent: 5,
    max_items_per_batch: 500,
    notification_channels: ['system'],
  },
};
