/**
 * 桌面菜单配置 - 独立模块
 * 与 DashboardDesktop.jsx 解耦，便于独立维护菜单项
 */
import React from 'react';
import {
  DashboardOutlined,
  AppstoreOutlined,
  SwapOutlined,
  GiftOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  SettingOutlined,
  EnvironmentOutlined,
  UserOutlined,
  DollarOutlined,
  AuditOutlined,
  CheckCircleOutlined,
  RobotOutlined,
  ExperimentOutlined,
  WarningOutlined,
  AlertOutlined,
  SafetyOutlined,
  MessageOutlined,
  ToolOutlined,
  BarChartOutlined,
  TeamOutlined,
  FileDoneOutlined,
  QrcodeOutlined,
  ShopOutlined,
} from '@ant-design/icons';

export const desktopMenuItems = [
  {
    key: 'dashboard',
    icon: <DashboardOutlined />,
    label: '仪表盘',
    color: '#0a84ff',
    path: '/dashboard',
    children: [
      { key: 'asset-big-screen', label: '资产状态大屏', path: '/asset-dashboard', icon: <DashboardOutlined /> },
    ],
  },
  {
    key: 'ai-assistant',
    icon: <RobotOutlined />,
    label: 'AI助手',
    color: '#0a84ff',
    path: '/ai-assistant',
    children: [
      { key: 'ai-assistant-main', label: '资产AI助手', path: '/ai-assistant' },
    ],
  },
  {
    key: 'assets',
    icon: <AppstoreOutlined />,
    label: '资产主数据',
    color: '#0a84ff',
    path: '/assets',
    children: [
      { key: 'assets-list', label: '资产列表', path: '/assets' },
      { key: 'assets-add', label: '添加资产', path: '/assets/add' },
      { key: 'temp-assets', label: '临时资产', path: '/temp-assets' },
      { key: 'asset-labels-templates', label: '标签模板管理', path: '/asset-labels/templates' },
      { key: 'asset-labels-print', label: '标签打印', path: '/asset-labels/print' },
      { key: 'assets-import', label: '导入资产', path: '/assets/import' },
    ],
  },
  {
    key: 'depreciation',
    icon: <DollarOutlined />,
    label: '折旧管理',
    color: '#f59e0b',
    path: '/depreciation',
    children: [
      { key: 'depreciation-list', label: '资产折旧', path: '/depreciation' },
    ],
  },
  {
    key: 'inventory',
    icon: <FileSearchOutlined />,
    label: '盘点管理',
    color: '#10b981',
    path: '/inventory',
    children: [
      { key: 'inventory-list', label: '资产盘点列表', path: '/inventory' },
      { key: 'inventory-self', label: '我的资产盘点', path: '/inventory/self' },
      { key: 'inventory-new', label: '新建盘点', path: '/inventory/new' },
    ],
  },
  {
    key: 'transfer',
    icon: <SwapOutlined />,
    label: '资产调配',
    color: '#f59e0b',
    path: '/transfer',
    children: [
      { key: 'transfer-list', label: '调配记录', path: '/transfer' },
      { key: 'transfer-new', label: '调配申请', path: '/transfer/new' },
      { key: 'transfer-requests', label: '调配申请处理', path: '/transfer/requests' },
    ],
  },
  {
    key: 'idle',
    icon: <GiftOutlined />,
    label: '闲置资产',
    color: '#ec4899',
    path: '/idle',
    children: [
      { key: 'idle-list', label: '闲置资产列表', path: '/idle' },
      { key: 'idle-new', label: '新增闲置资产', path: '/idle/new' },
    ],
  },
  {
    key: 'maintenance',
    icon: <ToolOutlined />,
    label: '维修维护',
    color: '#ef4444',
    path: '/maintenance/workorders',
    children: [
      { key: 'maintenance-plans', label: '预防性维护', path: '/maintenance/plans' },
      { key: 'maintenance-templates', label: '维护计划模板', path: '/maintenance/templates' },
      { key: 'maintenance-requests', label: '维修申请', path: '/maintenance/requests' },
      { key: 'maintenance-workorders', label: '调度中心', path: '/maintenance/workorders' },
      { key: 'maintenance-efficiency', label: '维护效率分析', path: '/maintenance/efficiency' },
      { key: 'maintenance-reminders', label: '维护提醒管理', path: '/maintenance/reminders' },
      { key: 'usage-triggers', label: '阈值触发管理', path: '/maintenance/usage-triggers' },
      { key: 'asset-usage', label: '资产使用量管理', path: '/maintenance/asset-usage' },
      { key: 'maintenance-costs', label: '维护成本管理', path: '/maintenance/costs' },
      { key: 'maintenance-evaluations', label: '维护效果评估', path: '/maintenance/evaluations' },
    ],
  },
  {
    key: 'asset-monitoring',
    icon: <EnvironmentOutlined />,
    label: '资产定位与IoT',
    color: '#06b6d4',
    path: '/asset-location',
    children: [
      { key: 'asset-location', label: '地理定位', path: '/asset-location' },
      { key: 'beacon-location', label: '区域定位', path: '/beacon-location' },
      { key: 'iot-devices', label: 'IoT设备管理', path: '/iot-devices' },
      { key: 'asset-monitoring', label: '资产监测', path: '/asset-monitoring' },
      { key: 'environment-monitoring', label: '环境监测', path: '/environment-monitoring' },
    ],
  },
  {
    key: 'quality',
    icon: <ExperimentOutlined />,
    label: '质量管理',
    color: '#5e5ce6',
    path: '/quality-control/metrology',
    children: [
      { key: 'metrology', label: '计量管理', path: '/quality-control/metrology' },
      { key: 'metrology-management', label: '计量管理页', path: '/quality-control/metrology-page' },
      { key: 'quality-qc', label: '质控管理', path: '/quality-control/qc' },
      { key: 'quality-statistics', label: '统计分析', path: '/quality-control/statistics' },
      { key: 'quality-management', label: '质量管理总览', path: '/quality-control/management' },
      { key: 'adverse-reaction', label: '不良事件管理', path: '/adverse-reaction' },
      { key: 'metrology-upload', label: '报告智能识别', path: '/quality-control/metrology-upload' },
    ],
  },
  {
    key: 'technical-documents',
    icon: <FileTextOutlined />,
    label: '技术资料',
    color: '#f97316',
    path: '/technical-documents',
    children: [
      { key: 'docs-list', label: '资料列表', path: '/technical-documents' },
      { key: 'docs-upload', label: '资料上传', path: '/technical-documents/upload' },
      { key: 'docs-batch-upload', label: '资料批量上传', path: '/technical-documents/batch-upload' },
      { key: 'docs-review', label: '资料审核', path: '/technical-documents/review' },
    ],
  },
  {
    key: 'acceptance',
    icon: <CheckCircleOutlined />,
    label: '验收管理',
    color: '#22c55e',
    path: '/acceptance',
    children: [
      { key: 'acceptance-list', label: '验收记录', path: '/acceptance' },
      { key: 'acceptance-create', label: '创建验收记录', path: '/acceptance/create' },
    ],
  },
  {
    key: 'suppliers',
    icon: <ShopOutlined />,
    label: '供应商管理',
    color: '#0ea5e9',
    path: '/tendering/suppliers',
    children: [],
  },
  {
    key: 'tendering',
    icon: <AuditOutlined />,
    label: '招标采购',
    color: '#8b5cf6',
    path: '/tendering/dashboard',
    children: [
      { key: 'tendering-dashboard', label: '招标概览', path: '/tendering/dashboard', icon: <BarChartOutlined /> },
      { key: 'tendering-projects', label: '招标项目管理', path: '/tendering/projects', icon: <FileTextOutlined /> },
      { key: 'tendering-bids', label: '投标管理', path: '/tendering/bids', icon: <FileDoneOutlined /> },
      { key: 'tendering-evaluations', label: '评标管理', path: '/tendering/evaluations', icon: <CheckCircleOutlined /> },
      { key: 'tendering-public', label: '公开扫码入口', path: '/tendering/qrcodes', icon: <QrcodeOutlined /> },
    ],
  },
  {
    key: 'special-equipment',
    icon: <AlertOutlined />,
    label: '特种设备管理',
    color: '#f59e0b',
    path: '/special-equipment',
    children: [
      { key: 'special-equipment-list', label: '特种设备', path: '/special-equipment' },
    ],
  },
  {
    key: 'compliance',
    icon: <SafetyOutlined />,
    label: '合规模块',
    color: '#14b8a6',
    path: '/compliance',
    children: [
      { key: 'compliance-dashboard', label: '合规仪表盘', path: '/compliance' },
      { key: 'maintenance-level', label: '维护等级', path: '/compliance/maintenance-level' },
      { key: 'safety-inspection', label: '安全巡检', path: '/safety-inspection' },
    ],
  },
  {
    key: 'risk',
    icon: <WarningOutlined />,
    label: '风险管理',
    color: '#dc2626',
    path: '/risk',
    children: [
      { key: 'risk-dashboard', label: '风险仪表盘', path: '/risk' },
      { key: 'risk-assessment', label: '风险评估', path: '/risk/assessment' },
      { key: 'risk-classification', label: '风险分类', path: '/risk/classification' },
      { key: 'risk-control', label: '风险控制', path: '/risk/control' },
    ],
  },
  {
    key: 'staff',
    icon: <UserOutlined />,
    label: '人员资质',
    color: '#64748b',
    path: '/staff',
    children: [
      { key: 'staff-dashboard', label: '人员仪表盘', path: '/staff' },
      { key: 'staff-qualifications', label: '资质管理', path: '/staff/qualifications' },
      { key: 'staff-training', label: '培训管理', path: '/staff/training' },
      { key: 'staff-assessments', label: '能力评估', path: '/staff/assessments' },
    ],
  },
  {
    key: 'uptime',
    icon: <DashboardOutlined />,
    label: '开机率管理',
    color: '#0ea5e9',
    path: '/uptime',
    children: [
      { key: 'uptime-dashboard', label: '开机率仪表盘', path: '/uptime' },
      { key: 'uptime-overview', label: '开机率概览', path: '/uptime/overview' },
      { key: 'uptime-operation-logs', label: '运行日志', path: '/uptime/operation-logs' },
      { key: 'uptime-statistics', label: '开机率统计', path: '/uptime/statistics' },
    ],
  },
  {
    key: 'system',
    icon: <SettingOutlined />,
    label: '系统管理',
    color: '#6b7280',
    path: '/modules',
    children: [
      { key: 'modules', label: '模块管理', path: '/modules' },
      { key: 'tenants', label: '企业管理', path: '/tenants' },
      { key: 'users', label: '用户管理', path: '/users' },
      { key: 'departments', label: '部门管理', path: '/departments' },
      { key: 'roles-permissions', label: '权限管理', path: '/roles-permissions' },
      { key: 'tenant-module-config', label: '模块设置', path: '/tenant-module-config' },
      { key: 'dashboard-configs', label: '仪表盘配置', path: '/dashboard-configs' },
      { key: 'cloud-sync', label: '云/IoT同步', path: '/cloud-sync' },
      { key: 'audit-logs', label: '操作日志', path: '/audit-logs' },
      { key: 'audit-management', label: '审计日志管理', path: '/audit-management' },
      { key: 'backup', label: '数据库备份', path: '/backup' },
      { key: 'database-connection', label: '数据库连接管理', path: '/database-connection' },
      { key: 'api-docs', label: 'Swagger API文档', path: '/api-docs' },
      { key: 'api-documentation', label: '完整API文档', path: '/api-documentation' },
      { key: 'token-management', label: 'Token管理', path: '/system/token-management' },
    ],
  },
];
