module.exports = {
  id: 'tendering-management',
  name: '招标采购管理',
  version: '1.0.0',
  description: '招标采购模块，覆盖资产购置招标文件制作、资产配件/维修服务招标、供应商扫码二维码上传资质、合同签订全流程闭环。',
  category: '资产生命周期',
  type: 'system',
  status: 'stable',
  author: 'System Team',
  created_at: '2026-07-07T00:00:00Z',
  updated_at: '2026-07-11T00:00:00Z',

  dependencies: [
    {
      module_id: 'asset-management',
      dependency_type: 'optional',
      min_version: '1.0.0',
      max_version: '2.0.0',
    },
  ],

  compatibility: [],

  frontend_config: {
    menu_keys: [
      '/tendering',
      '/tendering/requests',
      '/tendering/requests/new',
      '/tendering/requests/:id',
      '/tendering/projects',
      '/tendering/projects/new',
      '/tendering/projects/edit/:id',
      '/tendering/projects/:id',
      '/tendering/projects/:id/document',
      '/tendering/suppliers',
      '/tendering/contracts',
      '/tendering/contracts/new',
      '/tendering/contracts/edit/:id',
      '/tendering/contracts/:id',
      '/tendering/invoices',
      '/tendering/invoices/new',
      '/tendering/invoices/:id',
      '/tendering/payments',
      '/tendering/payments/new',
      '/tendering/payments/:id',
      '/tendering/acceptances',
      '/tendering/acceptances/new',
      '/tendering/acceptances/:id',
      '/tendering/audits',
      '/tendering/statistics',
    ],
    menu_prefixes: ['/tendering'],
    menu_routes: [
      {
        key: '/tendering',
        icon: 'AuditOutlined',
        label: '采购与招标',
        path: '/tendering/projects',
        component: 'TenderProjectList',
        permissions: ['tendering:read'],
      },
      {
        key: '/tendering/requests',
        label: '采购申请',
        path: '/tendering/requests',
        component: 'TenderRequestList',
        permissions: ['tendering:request:read'],
      },
      {
        key: '/tendering/projects',
        label: '招标项目',
        path: '/tendering/projects',
        component: 'TenderProjectList',
        permissions: ['tendering:read'],
      },
      {
        key: '/tendering/suppliers',
        label: '供应商',
        path: '/tendering/suppliers',
        component: 'SupplierList',
        permissions: ['tendering:supplier:read'],
      },
      {
        key: '/tendering/contracts',
        label: '合同',
        path: '/tendering/contracts',
        component: 'ContractList',
        permissions: ['tendering:contract:read'],
      },
      {
        key: '/tendering/invoices',
        label: '发票管理',
        path: '/tendering/invoices',
        component: 'TenderInvoiceList',
        permissions: ['tendering:invoice:read'],
      },
      {
        key: '/tendering/payments',
        label: '付款管理',
        path: '/tendering/payments',
        component: 'TenderPaymentList',
        permissions: ['tendering:payment:read'],
      },
      {
        key: '/tendering/acceptances',
        label: '验收管理',
        path: '/tendering/acceptances',
        component: 'TenderAcceptanceList',
        permissions: ['tendering:acceptance:read'],
      },
      {
        key: '/tendering/audits',
        label: '审计日志',
        path: '/tendering/audits',
        component: 'TenderAuditList',
        permissions: ['tendering:audit:read'],
      },
      {
        key: '/tendering/statistics',
        label: '采购与招标统计',
        path: '/tendering/statistics',
        component: 'TenderStatistics',
        permissions: ['tendering:read'],
      },
    ],
    components: [
      { name: 'TenderProjectList', path: 'pages/tendering/TenderProjectList', export: 'default' },
      { name: 'TenderProjectForm', path: 'pages/tendering/TenderProjectForm', export: 'default' },
      { name: 'TenderProjectDetail', path: 'pages/tendering/TenderProjectDetail', export: 'default' },
      { name: 'TenderDocumentEditor', path: 'pages/tendering/TenderDocumentEditor', export: 'default' },
      { name: 'SupplierList', path: 'pages/tendering/SupplierList', export: 'default' },
      { name: 'SupplierQualificationUpload', path: 'pages/tendering/SupplierQualificationUpload', export: 'default' },
      { name: 'ContractList', path: 'pages/tendering/ContractList', export: 'default' },
      { name: 'ContractForm', path: 'pages/tendering/ContractForm', export: 'default' },
      { name: 'ContractDetail', path: 'pages/tendering/ContractDetail', export: 'default' },
      { name: 'TenderRequestList', path: 'pages/tendering/TenderRequestList', export: 'default' },
      { name: 'TenderRequestForm', path: 'pages/tendering/TenderRequestForm', export: 'default' },
      { name: 'TenderRequestDetail', path: 'pages/tendering/TenderRequestDetail', export: 'default' },
      { name: 'TenderInvoiceList', path: 'pages/tendering/TenderInvoiceList', export: 'default' },
      { name: 'TenderInvoiceForm', path: 'pages/tendering/TenderInvoiceForm', export: 'default' },
      { name: 'TenderInvoiceDetail', path: 'pages/tendering/TenderInvoiceDetail', export: 'default' },
      { name: 'AssetInvoiceForm', path: 'pages/tendering/AssetInvoiceForm', export: 'default' },
      { name: 'TenderPaymentList', path: 'pages/tendering/TenderPaymentList', export: 'default' },
      { name: 'TenderPaymentForm', path: 'pages/tendering/TenderPaymentForm', export: 'default' },
      { name: 'TenderPaymentDetail', path: 'pages/tendering/TenderPaymentDetail', export: 'default' },
      { name: 'TenderAcceptanceList', path: 'pages/tendering/TenderAcceptanceList', export: 'default' },
      { name: 'TenderAcceptanceForm', path: 'pages/tendering/TenderAcceptanceForm', export: 'default' },
      { name: 'TenderAcceptanceDetail', path: 'pages/tendering/TenderAcceptanceDetail', export: 'default' },
      { name: 'TenderAuditList', path: 'pages/tendering/TenderAuditList', export: 'default' },
      { name: 'TenderApprovalTodo', path: 'pages/tendering/TenderApprovalTodo', export: 'default' },
      { name: 'TenderApprovalFlows', path: 'pages/tendering/TenderApprovalFlows', export: 'default' },
    ],
    permissions: [
      'tendering:read',
      'tendering:create',
      'tendering:update',
      'tendering:delete',
      'tendering:publish',
      'tendering:evaluate',
      'tendering:supplier:read',
      'tendering:supplier:create',
      'tendering:supplier:update',
      'tendering:supplier:review',
      'tendering:file:upload',
      'tendering:contract:read',
      'tendering:contract:create',
      'tendering:contract:update',
      'tendering:contract:delete',
      'tendering:contract:approve',
      'tendering:contract:sign',
      'tendering:contract:archive',
      'tendering:request:read',
      'tendering:request:create',
      'tendering:request:update',
      'tendering:request:approve',
      'tendering:simple:approve',
      'tendering:invoice:read',
      'tendering:invoice:create',
      'tendering:invoice:update',
      'tendering:invoice:submit',
      'tendering:invoice:verify',
      'tendering:invoice:claim',
      'tendering:invoice:pay',
      'tendering:invoice:archive',
      'tendering:invoice:cancel',
      'tendering:invoice:retry',
      'tendering:invoice:statistics:read',
      'tendering:payment:read',
      'tendering:payment:create',
      'tendering:payment:update',
      'tendering:payment:submit',
      'tendering:payment:execute',
      'tendering:payment:fail',
      'tendering:payment:cancel',
      'tendering:acceptance:read',
      'tendering:acceptance:create',
      'tendering:acceptance:update',
      'tendering:acceptance:accept',
      'tendering:acceptance:reject',
      'tendering:acceptance:close',
      'tendering:audit:read',
    ],
  },

  backend_config: {
    api_endpoints: [
      // 字典（无需鉴权，方便前端初始化）
      { method: 'GET', path: '/api/tendering/dict', handler: 'getDict', permissions: [], controller: 'TenderingController' },

      // 招标项目
      { method: 'GET', path: '/api/tendering/projects', handler: 'listTenders', permissions: ['tendering:read'], controller: 'TenderingController' },
      { method: 'GET', path: '/api/tendering/projects/:id', handler: 'getTender', permissions: ['tendering:read'], controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/projects', handler: 'createTender', permissions: ['tendering:create'], controller: 'TenderingController' },
      { method: 'PUT', path: '/api/tendering/projects/:id', handler: 'updateTender', permissions: ['tendering:update'], controller: 'TenderingController' },
      { method: 'PUT', path: '/api/tendering/projects/:id/status', handler: 'changeTenderStatus', permissions: ['tendering:publish'], controller: 'TenderingController' },
      { method: 'DELETE', path: '/api/tendering/projects/:id', handler: 'deleteTender', permissions: ['tendering:delete'], controller: 'TenderingController' },

      // 招标文件制作
      { method: 'GET', path: '/api/tendering/projects/:id/sections', handler: 'listSections', permissions: ['tendering:read'], controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/projects/:id/sections', handler: 'upsertSection', permissions: ['tendering:update'], controller: 'TenderingController' },
      { method: 'PUT', path: '/api/tendering/projects/:id/sections/:sectionCode', handler: 'upsertSection', permissions: ['tendering:update'], controller: 'TenderingController' },
      { method: 'DELETE', path: '/api/tendering/projects/:id/sections/:sectionCode', handler: 'deleteSection', permissions: ['tendering:update'], controller: 'TenderingController' },

      // 招标附件
      { method: 'GET', path: '/api/tendering/projects/:id/files', handler: 'listTenderFiles', permissions: ['tendering:read'], controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/projects/:id/files', handler: 'uploadTenderFile', permissions: ['tendering:file:upload'], controller: 'TenderingController' },
      { method: 'DELETE', path: '/api/tendering/files/:fileId', handler: 'deleteTenderFile', permissions: ['tendering:delete'], controller: 'TenderingController' },

      // 供应商管理
      { method: 'GET', path: '/api/tendering/suppliers', handler: 'listSuppliers', permissions: ['tendering:supplier:read'], controller: 'TenderingController' },
      { method: 'GET', path: '/api/tendering/suppliers/:id', handler: 'getSupplier', permissions: ['tendering:supplier:read'], controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/suppliers', handler: 'createSupplier', permissions: ['tendering:supplier:create'], controller: 'TenderingController' },
      { method: 'PUT', path: '/api/tendering/suppliers/:id', handler: 'updateSupplier', permissions: ['tendering:supplier:update'], controller: 'TenderingController' },
      { method: 'PUT', path: '/api/tendering/suppliers/:id/status', handler: 'setSupplierStatus', permissions: ['tendering:supplier:update'], controller: 'TenderingController' },
      { method: 'DELETE', path: '/api/tendering/suppliers/:id', handler: 'deleteSupplier', permissions: ['tendering:supplier:update'], controller: 'TenderingController' },

      // 供应商扫码上传资质 token
      { method: 'POST', path: '/api/tendering/suppliers/:id/qr-token', handler: 'generateSupplierToken', permissions: ['tendering:supplier:update'], controller: 'TenderingController' },

      // 供应商资质查看与审核
      { method: 'GET', path: '/api/tendering/suppliers/:id/qualifications', handler: 'listQualifications', permissions: ['tendering:supplier:read'], controller: 'TenderingController' },
      { method: 'PUT', path: '/api/tendering/qualifications/:qualificationId/review', handler: 'reviewQualification', permissions: ['tendering:supplier:review'], controller: 'TenderingController' },

      // 招标邀请（生成邀请二维码）
      { method: 'GET', path: '/api/tendering/projects/:id/invitations', handler: 'listInvitations', permissions: ['tendering:read'], controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/projects/:id/invitations', handler: 'inviteSupplier', permissions: ['tendering:update'], controller: 'TenderingController' },

      // 投标记录
      { method: 'GET', path: '/api/tendering/projects/:id/bids', handler: 'listBids', permissions: ['tendering:read'], controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/projects/:id/bids', handler: 'submitBid', permissions: ['tendering:supplier:create'], controller: 'TenderingController' },
      { method: 'GET', path: '/api/tendering/bids/:bidId', handler: 'getBid', permissions: ['tendering:read'], controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/bids/:bidId/withdraw', handler: 'withdrawBid', permissions: ['tendering:supplier:update'], controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/projects/:id/award', handler: 'awardBid', permissions: ['tendering:publish'], controller: 'TenderingController' },

      // 评标
      { method: 'GET', path: '/api/tendering/projects/:id/evaluations', handler: 'listEvaluations', permissions: ['tendering:read'], controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/projects/:id/evaluations', handler: 'submitEvaluation', permissions: ['tendering:evaluate'], controller: 'TenderingController' },
      { method: 'GET', path: '/api/tendering/projects/:id/evaluations/summary', handler: 'summarizeEvaluations', permissions: ['tendering:read'], controller: 'TenderingController' },

      // 统计概览
      { method: 'GET', path: '/api/tendering/statistics', handler: 'getStatistics', permissions: ['tendering:read'], controller: 'TenderingController' },

      // 招标项目分享 token（项目级二维码）
      { method: 'POST', path: '/api/tendering/projects/:id/share-tokens', handler: 'generateShareToken', permissions: ['tendering:publish'], controller: 'TenderingController' },
      { method: 'GET', path: '/api/tendering/projects/:id/share-tokens', handler: 'listShareTokens', permissions: ['tendering:read'], controller: 'TenderingController' },
      { method: 'DELETE', path: '/api/tendering/share-tokens/:tokenId', handler: 'revokeShareToken', permissions: ['tendering:publish'], controller: 'TenderingController' },

      // 合同管理（定标→合同签订→完成闭环）
      { method: 'GET', path: '/api/tendering/contracts', handler: 'listContracts', permissions: ['tendering:contract:read'], controller: 'TenderingController' },
      { method: 'GET', path: '/api/tendering/contracts/statistics', handler: 'getContractStatistics', permissions: ['tendering:contract:read'], controller: 'TenderingController' },
      { method: 'GET', path: '/api/tendering/contracts/:id', handler: 'getContract', permissions: ['tendering:contract:read'], controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/contracts', handler: 'createContract', permissions: ['tendering:contract:create'], controller: 'TenderingController' },
      { method: 'PUT', path: '/api/tendering/contracts/:id', handler: 'updateContract', permissions: ['tendering:contract:update'], controller: 'TenderingController' },
      { method: 'PUT', path: '/api/tendering/contracts/:id/status', handler: 'changeContractStatus', permissions: ['tendering:contract:update'], controller: 'TenderingController' },
      { method: 'DELETE', path: '/api/tendering/contracts/:id', handler: 'deleteContract', permissions: ['tendering:contract:delete'], controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/contracts/:id/files', handler: 'uploadContractFile', permissions: ['tendering:contract:update'], controller: 'TenderingController' },
      { method: 'DELETE', path: '/api/tendering/contracts/files/:fileId', handler: 'deleteContractFile', permissions: ['tendering:contract:delete'], controller: 'TenderingController' },
      { method: 'GET', path: '/api/tendering/projects/:id/contracts', handler: 'listContractsByTender', permissions: ['tendering:contract:read'], controller: 'TenderingController' },

      // 公开接口：供应商扫码上传资质（免登录）
      { method: 'GET', path: '/api/tendering/public/supplier/:token', handler: 'getSupplierByToken', permissions: [], controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/public/supplier/:token/qualifications', handler: 'uploadQualificationByToken', permissions: [], controller: 'TenderingController' },

      // 公开接口：项目分享二维码（免登录，任意扫码者）
      { method: 'GET', path: '/api/tendering/public/tender/:token', handler: 'publicGetTender', permissions: [], controller: 'TenderingController' },
      { method: 'GET', path: '/api/tendering/public/tender/:token/files', handler: 'publicListFiles', permissions: [], controller: 'TenderingController' },
      { method: 'GET', path: '/api/tendering/public/tender/:token/files/:fileId', handler: 'publicDownloadFile', permissions: [], controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/public/tender/:token/qualifications', handler: 'publicUploadQualification', permissions: [], controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/public/tender/:token/bids', handler: 'publicSubmitBid', permissions: [], controller: 'TenderingController' },

      // 健康检查与根路径
      { method: 'GET', path: '/api/tendering/health', handler: null, permissions: [], controller: null },

      // ==================== 采购申请（前置于招标流程） ====================
      { method: 'GET',  path: '/api/tendering/procurement-requests',          handler: 'listProcurementRequests',  permissions: ['tendering:request:read'],   controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/procurement-requests',          handler: 'createProcurementRequest', permissions: ['tendering:request:create'], controller: 'TenderingController' },
      { method: 'GET',  path: '/api/tendering/procurement-requests/:id',      handler: 'getProcurementRequest',    permissions: ['tendering:request:read'],   controller: 'TenderingController' },
      { method: 'PUT',  path: '/api/tendering/procurement-requests/:id',      handler: 'updateProcurementRequest',  permissions: ['tendering:request:update'], controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/procurement-requests/:id/submit',   handler: 'submitProcurementRequest',   permissions: ['tendering:request:update'], controller: 'TenderingController' },
      { method: 'PUT',  path: '/api/tendering/procurement-requests/:id/approve', handler: 'approveProcurementRequest',  permissions: ['tendering:request:approve'],controller: 'TenderingController' },
      { method: 'DELETE', path: '/api/tendering/procurement-requests/:id',    handler: 'deleteProcurementRequest',  permissions: ['tendering:request:update'], controller: 'TenderingController' },

      // ==================== 发票管理 ====================
      { method: 'GET',  path: '/api/tendering/invoices',                          handler: 'listInvoices',         permissions: ['tendering:invoice:read'],                 controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/invoices',                          handler: 'createInvoice',        permissions: ['tendering:invoice:create'],              controller: 'TenderingController' },
      { method: 'GET',  path: '/api/tendering/invoices/statistics',               handler: 'getInvoiceStatistics', permissions: ['tendering:invoice:statistics:read'],     controller: 'TenderingController' },
      { method: 'GET',  path: '/api/tendering/invoices/:id',                      handler: 'getInvoice',           permissions: ['tendering:invoice:read'],                 controller: 'TenderingController' },
      { method: 'PUT',  path: '/api/tendering/invoices/:id',                      handler: 'updateInvoice',        permissions: ['tendering:invoice:update'],               controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/invoices/:id/submit',               handler: 'submitInvoice',        permissions: ['tendering:invoice:submit'],               controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/invoices/:id/verify',               handler: 'verifyInvoice',        permissions: ['tendering:invoice:verify'],               controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/invoices/:id/verify-fail',           handler: 'failVerifyInvoice',    permissions: ['tendering:invoice:verify'],               controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/invoices/:id/retry',                handler: 'retryInvoice',         permissions: ['tendering:invoice:retry'],                controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/invoices/:id/claim',                handler: 'claimInvoice',         permissions: ['tendering:invoice:claim'],                controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/invoices/:id/pay',                  handler: 'payInvoice',           permissions: ['tendering:invoice:pay'],                  controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/invoices/:id/archive',              handler: 'archiveInvoice',       permissions: ['tendering:invoice:archive'],              controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/invoices/:id/cancel',               handler: 'cancelInvoice',        permissions: ['tendering:invoice:cancel'],               controller: 'TenderingController' },
      { method: 'DELETE', path: '/api/tendering/invoices/:id',                    handler: 'deleteInvoice',        permissions: ['tendering:invoice:update'],               controller: 'TenderingController' },
      { method: 'POST',   path: '/api/tendering/invoices/:id/milestone',           handler: 'generateMilestoneFromInvoice', permissions: ['tendering:invoice:update'],        controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/invoices/:id/files',                handler: 'uploadInvoiceFile',    permissions: ['tendering:invoice:update'],               controller: 'TenderingController' },
      { method: 'DELETE', path: '/api/tendering/invoices/files/:fileId',          handler: 'deleteInvoiceFile',    permissions: ['tendering:invoice:update'],               controller: 'TenderingController' },
      { method: 'POST', path: '/api/tendering/assets/:assetId/invoice',           handler: 'createInvoiceFromAsset', permissions: ['tendering:invoice:create'],            controller: 'TenderingController' },
    ],
    database_tables: [
      'approval_flows',
      'approval_nodes',
      'approval_records',
      'approval_node_records',
      'approval_todos',
      'tender_projects',
      'tender_documents',
      'tender_files',
      'tender_suppliers',
      'tender_supplier_qualifications',
      'tender_invitations',
      'tender_bids',
      'tender_evaluations',
      'tender_share_tokens',
      'tender_share_visits',
      'tender_share_bids',
      'tender_contracts',
      'tender_contract_files',
      'tender_payment_milestones',
      'tender_invoices',
      'tender_invoice_files',
      'tender_payments',
      'tender_payment_files',
      'tender_acceptances',
      'tender_acceptance_files',
      'tender_audit_logs',
    ],
    services: [
      { name: 'TenderingService', path: 'services/tendering.service' },
      { name: 'ProcurementRequestService', path: 'services/procurement-request.service' },
      { name: 'TenderingInvoiceService', path: 'services/tender-invoice.service' },
      { name: 'TenderingPaymentService', path: 'services/tender-payment.service' },
      { name: 'TenderingAcceptanceService', path: 'services/tender-acceptance.service' },
      { name: 'TenderingAuditLogService', path: 'services/tender-audit-log.service' },
      { name: 'MiniMaxClient', path: 'services/minimax-client.service' },
      { name: 'AIApprovalAssistant', path: 'services/ai-approval-assistant.service' },
    ],
    permissions: [
      'tendering:read',
      'tendering:create',
      'tendering:update',
      'tendering:delete',
      'tendering:publish',
      'tendering:evaluate',
      'tendering:supplier:read',
      'tendering:supplier:create',
      'tendering:supplier:update',
      'tendering:supplier:review',
      'tendering:file:upload',
      'tendering:contract:read',
      'tendering:contract:create',
      'tendering:contract:update',
      'tendering:contract:delete',
      'tendering:contract:approve',
      'tendering:contract:sign',
      'tendering:contract:archive',
      'tendering:request:read',
      'tendering:request:create',
      'tendering:request:update',
      'tendering:request:approve',
      'tendering:simple:approve',
    ],
  },

  config_schema: [
    {
      key: 'default_qr_valid_days',
      name: '二维码默认有效天数',
      type: 'number',
      required: false,
      default: 30,
      group: '供应商设置',
      description: '供应商扫码上传资质二维码的默认有效期。',
      validation: { min: 1, max: 365 },
    },
    {
      key: 'auto_qualify_when_all_approved',
      name: '资质全通过自动合格',
      type: 'boolean',
      required: false,
      default: true,
      group: '供应商设置',
      description: '当供应商全部资质材料审核通过后，自动将其状态置为合格。',
    },
    {
      key: 'enable_bidding_stage',
      name: '启用投标环节',
      type: 'boolean',
      required: false,
      default: true,
      group: '流程设置',
      description: '招标发布后是否启用供应商投标环节。',
    },
  ],
  default_config: {
    default_qr_valid_days: 30,
    auto_qualify_when_all_approved: true,
    enable_bidding_stage: true,
  },
};
