module.exports = {
  id: 'acceptance-management',
  name: '验收管理',
  version: '2.0.0',
  description: '提供验收申请、审批工作流、验收单、检查清单、验收报告、模板管理等完整验收能力。',
  category: '资产管理',
  type: 'system',
  status: 'stable',
  author: 'System Team',
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2026-06-26T00:00:00Z',

  dependencies: [
    {
      module_id: 'asset-management',
      dependency_type: 'required',
      min_version: '1.0.0',
      max_version: '2.0.0',
    },
    {
      module_id: 'user-management',
      dependency_type: 'required',
      min_version: '1.0.0',
    },
  ],

  frontend_config: {
    menu_keys: [
      '/acceptance',
      '/acceptance/create',
      '/acceptance/applications',
      '/acceptance/templates',
      '/acceptance/statistics',
      '/acceptance/reminders',
    ],
    menu_routes: [
      {
        key: '/acceptance',
        icon: 'CheckCircleOutlined',
        label: '验收记录',
        path: '/acceptance',
        component: 'AcceptanceList',
        permissions: ['acceptance:record:read'],
      },
      {
        key: '/acceptance/applications',
        icon: 'FileSearchOutlined',
        label: '验收申请',
        path: '/acceptance/applications',
        component: 'AcceptanceApplicationList',
        permissions: ['acceptance:application:read'],
      },
      {
        key: '/acceptance/templates',
        icon: 'ProfileOutlined',
        label: '验收模板',
        path: '/acceptance/templates',
        component: 'AcceptanceTemplateList',
        permissions: ['acceptance:template:read'],
      },
      {
        key: '/acceptance/statistics',
        icon: 'BarChartOutlined',
        label: '验收统计',
        path: '/acceptance/statistics',
        component: 'AcceptanceStatistics',
        permissions: ['acceptance:statistics:read'],
      },
      {
        key: '/acceptance/reminders',
        icon: 'BellOutlined',
        label: '验收提醒',
        path: '/acceptance/reminders',
        component: 'AcceptanceReminders',
        permissions: ['acceptance:record:read'],
      },
    ],
    permissions: [
      'acceptance:record:read',
      'acceptance:record:create',
      'acceptance:record:update',
      'acceptance:record:delete',
      'acceptance:application:read',
      'acceptance:application:create',
      'acceptance:application:approve',
      'acceptance:application:withdraw',
      'acceptance:template:read',
      'acceptance:template:create',
      'acceptance:template:update',
      'acceptance:template:delete',
      'acceptance:report:read',
      'acceptance:report:generate',
      'acceptance:statistics:read',
      'acceptance:team:manage',
      'acceptance:reminder:manage',
    ],
  },

  backend_config: {
    api_endpoints: [
      { method: 'GET', path: '/api/acceptance-management/applications', permissions: ['acceptance:application:read'] },
      { method: 'POST', path: '/api/acceptance-management/applications', permissions: ['acceptance:application:create'] },
      { method: 'PUT', path: '/api/acceptance-management/applications/:id', permissions: ['acceptance:application:create'] },
      { method: 'POST', path: '/api/acceptance-management/applications/:id/submit', permissions: ['acceptance:application:create'] },
      { method: 'POST', path: '/api/acceptance-management/applications/:id/approve', permissions: ['acceptance:application:approve'] },
      { method: 'POST', path: '/api/acceptance-management/applications/:id/reject', permissions: ['acceptance:application:approve'] },
      { method: 'POST', path: '/api/acceptance-management/applications/:id/withdraw', permissions: ['acceptance:application:withdraw'] },
      { method: 'GET', path: '/api/acceptance-management/templates', permissions: ['acceptance:template:read'] },
      { method: 'POST', path: '/api/acceptance-management/templates', permissions: ['acceptance:template:create'] },
      { method: 'PUT', path: '/api/acceptance-management/templates/:id', permissions: ['acceptance:template:update'] },
      { method: 'DELETE', path: '/api/acceptance-management/templates/:id', permissions: ['acceptance:template:delete'] },
      { method: 'GET', path: '/api/acceptance-management/statistics/overview', permissions: ['acceptance:statistics:read'] },
      { method: 'GET', path: '/api/acceptance-management/statistics/trend', permissions: ['acceptance:statistics:read'] },
      { method: 'GET', path: '/api/acceptance-management/reports/:id', permissions: ['acceptance:report:read'] },
      { method: 'POST', path: '/api/acceptance-management/reports/:id/generate', permissions: ['acceptance:report:generate'] },
      { method: 'GET', path: '/api/acceptance-management/reminders', permissions: ['acceptance:record:read'] },
      { method: 'GET', path: '/api/acceptance-management/reminders/stats', permissions: ['acceptance:record:read'] },
      { method: 'POST', path: '/api/acceptance-management/reminders', permissions: ['acceptance:reminder:manage'] },
      { method: 'PUT', path: '/api/acceptance-management/reminders/:id/status', permissions: ['acceptance:reminder:manage'] },
      { method: 'DELETE', path: '/api/acceptance-management/reminders/:id', permissions: ['acceptance:reminder:manage'] },
      { method: 'GET', path: '/api/acceptance-management/teams/:recordId', permissions: ['acceptance:record:read'] },
      { method: 'POST', path: '/api/acceptance-management/teams/:recordId', permissions: ['acceptance:team:manage'] },
      { method: 'PUT', path: '/api/acceptance-management/teams/:recordId/:memberId', permissions: ['acceptance:team:manage'] },
      { method: 'DELETE', path: '/api/acceptance-management/teams/:recordId/:memberId', permissions: ['acceptance:team:manage'] },
    ],
    database_tables: [
      'asset_acceptance_records',
      'asset_acceptance_files',
      'asset_acceptance_checklist',
      'asset_acceptance_templates',
      'acceptance_applications',
      'acceptance_approvals',
      'acceptance_teams',
      'acceptance_reminders',
    ],
    permissions: [
      'acceptance:record:read',
      'acceptance:record:create',
      'acceptance:record:update',
      'acceptance:record:delete',
      'acceptance:application:read',
      'acceptance:application:create',
      'acceptance:application:approve',
      'acceptance:application:withdraw',
      'acceptance:template:read',
      'acceptance:template:create',
      'acceptance:template:update',
      'acceptance:template:delete',
      'acceptance:report:read',
      'acceptance:report:generate',
      'acceptance:statistics:read',
      'acceptance:team:manage',
      'acceptance:reminder:manage',
    ],
  },

  default_config: {
    max_applications_per_page: 50,
    auto_generate_report: true,
    reminder_lead_days: 3,
  },

  config_schema: [
    {
      key: 'max_applications_per_page',
      name: '每页最大申请数',
      type: 'number',
      default: 50,
      validation: { min: 10, max: 200 },
    },
    {
      key: 'reminder_lead_days',
      name: '提醒提前天数',
      type: 'number',
      default: 3,
      validation: { min: 1, max: 30 },
    },
  ],
};
